/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
              "on-primary-container": "#858383",
              "tertiary-container": "#002109",
              "on-tertiary-container": "#009842",
              "primary-fixed-dim": "#c8c6c5",
              "background": "#faf9f9",
              "surface-container": "#efeded",
              "outline": "#747878",
              "on-background": "#1b1c1c",
              "error": "#ba1a1a",
              "on-surface": "#1b1c1c",
              "on-error": "#ffffff",
              "surface-variant": "#e3e2e2",
              "on-error-container": "#93000a",
              "inverse-primary": "#c8c6c5",
              "secondary-fixed": "#dbe1ff",
              "on-tertiary": "#ffffff",
              "primary": "#000000",
              "on-tertiary-fixed-variant": "#005320",
              "surface-container-lowest": "#ffffff",
              "surface-bright": "#faf9f9",
              "on-secondary-fixed": "#00174b",
              "surface-container-low": "#f5f3f3",
              "on-secondary": "#ffffff",
              "primary-fixed": "#e5e2e1",
              "surface-container-highest": "#e3e2e2",
              "on-secondary-fixed-variant": "#003ea8",
              "primary-container": "#1c1b1b",
              "outline-variant": "#c4c7c7",
              "surface": "#faf9f9",
              "tertiary-fixed": "#7ffc97",
              "on-surface-variant": "#444748",
              "on-primary-fixed-variant": "#474646",
              "secondary-container": "#316bf3",
              "tertiary-fixed-dim": "#62df7d",
              "on-primary-fixed": "#1c1b1b",
              "secondary-fixed-dim": "#b4c5ff",
              "on-secondary-container": "#fefcff",
              "error-container": "#ffdad6",
              "on-primary": "#ffffff",
              "inverse-surface": "#303031",
              "on-tertiary-fixed": "#002109",
              "inverse-on-surface": "#f2f0f0",
              "secondary": "#0051d5",
              "tertiary": "#000000",
              "surface-dim": "#dbdad9",
              "surface-tint": "#5f5e5e",
              "surface-container-high": "#e9e8e8"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "sm": "16px",
              "lg": "48px",
              "xs": "8px",
              "xl": "80px",
              "offset-col": "120px",
              "md": "24px",
              "sidebar-width": "280px",
              "base": "4px"
      },
      "fontFamily": {
              "body-sm": ["Inter"],
              "headline-sm": ["Inter"],
              "headline-xl": ["Inter"],
              "code-md": ["JetBrains Mono"],
              "label-caps": ["JetBrains Mono"],
              "code-sm": ["JetBrains Mono"],
              "headline-lg": ["Inter"],
              "body-md": ["Inter"]
      },
      "fontSize": {
              "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
              "headline-sm": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
              "headline-xl": ["48px", {"lineHeight": "1.1", "fontWeight": "700"}],
              "code-md": ["14px", {"lineHeight": "1.6", "fontWeight": "450"}],
              "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "600"}],
              "code-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "450"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
